name = "neurapath-app"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-11-19"
minify = true
account_id = "6c2dccead5cc8b117a208576df3a8c2c"

routes = [
  { pattern = "app.neurapath.shop", custom_domain = true },
  { pattern = "www.app.neurapath.shop", custom_domain = true }
]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
ENVIRONMENT = "production"
TURNSTILE_SECRET_KEY="0x4AAAAAABrwaiIg84oUm8STEGh9Yztgzn4"
PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY="0x4AAAAAABrwau0ZWE5j8kEU"